env:
  node: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  quotes: ["error", "double"],
  semi: ["error", "always"]
}
